language: cpp

# Build with gcc and clang.
compiler:
  - gcc
# Disable clang for now since it seems there's a problem using it with fast fp math.
#  - clang

# Build both debug and release configurations, through use of an environment variable in the build matrix.
env:
  - CONFIGURATION=debug
  - CONFIGURATION=release

# Install SDL 1.2 development libraries.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl1.2-dev

# Run premake to generate makefiles.
# Have to cd into directory and back out since premake5 doesn't appear to accept a directory argument.
before_script:
  - cd RecastDemo && ../premake/premake5 gmake && cd ..

# Run make in the directory containing generated makefiles, on the configuration specified by the environment variable.
script:
  - make -C RecastDemo/Build/gmake config=$CONFIGURATION
