shallow_clone: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PREMAKE_ACTION: vs2013
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PREMAKE_ACTION: vs2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PREMAKE_ACTION: vs2017

configuration:
  - Debug
  - Release

install:
  # Download Premake
  - ps: Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-windows.zip' 'premake.zip'
  
  # Extract it in-place; premake5.exe is at the top level.
  - 7z x premake.zip

  # Download SDL.
  - ps: Start-FileDownload 'https://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip' 'RecastDemo/Contrib/SDL.zip'
  
  # Extract it, put it in the right place, and rename it.
  - cd RecastDemo\Contrib && 7z x SDL.zip && ren SDL2-2.0.4 SDL && cd ..\..
  
  # Generate solution files using premake.
  - cd RecastDemo && "../premake5.exe" %PREMAKE_ACTION% && cd ..


build:
  project: RecastDemo/Build/$(PREMAKE_ACTION)/recastnavigation.sln

after_test:
  - RecastDemo\Bin\Tests.exe
