name: CI Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  BUILD_TYPE: Release

jobs:
  build-premake-linux-debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup premake
      uses: abel0b/setup-premake@v2.1
      with:
        version: "5.0.0-beta1"

    - name: Install opengl + sdl
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libsdl2-dev

    - name: Generate project files
      working-directory: ./RecastDemo
      run: premake5 gmake

    - name: Build
      working-directory: ./RecastDemo/Build/gmake/
      run: make config=debug
