name: Build (macOS)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-premake:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Download & install SDL
      run: |
        curl -L -o SDL2.dmg https://github.com/libsdl-org/SDL/releases/download/release-2.24.2/SDL2-2.24.2.dmg
        hdiutil attach SDL2.dmg
        cp -r /Volumes/SDL2/SDL2.framework RecastDemo/Bin
        hdiutil detach /Volumes/SDL2
        rm SDL2.dmg
    - name: download premake
      working-directory: RecastDemo
      run: |
        curl -L -o premake.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-macosx.tar.gz
        tar -xzf premake.tar.gz
        rm premake.tar.gz

    - name: Run premake
      working-directory: RecastDemo
      run: ./premake5 xcode4

    - name: Build With Xcode
      working-directory: RecastDemo/Build/xcode4/
      run: xcodebuild -scheme RecastDemo -project RecastDemo.xcodeproj build
    
    - name: Build Unit Tests With Xcode
      working-directory: RecastDemo/Build/xcode4/
      run: xcodebuild -scheme Tests -project Tests.xcodeproj build

    - name: Run unit tests
      working-directory: RecastDemo/Bin
      run: ./Tests