name: Build (ubuntu)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-premake:
    strategy:
      matrix:
        conf:
          - debug
          - release
        compiler:
          - clang
          - gcc

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install opengl and SDL
      run: sudo apt-get install -y libgl1-mesa-dev libsdl2-dev

    - name: Download premake
      working-directory: RecastDemo
      run: |
        curl -L -o premake.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
        tar -xzf premake.tar.gz
        rm premake.tar.gz
    
    - name: Run premake
      working-directory: RecastDemo
      run: ./premake5 --cc=${{matrix.compiler}} gmake
    
    - name: Build
      working-directory: RecastDemo/Build/gmake
      run: make config=${{matrix.conf}}
    
    - name: Run Tests
      working-directory: RecastDemo/Bin
      run: ./Tests
    
  build-cmake:
    strategy:
      matrix:
        conf:
          - Debug
          - Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install opengl and SDL
      run: sudo apt-get install -y libgl1-mesa-dev libsdl2-dev

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.conf}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.conf}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
  