name: Build (windows)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-premake:
    strategy:
      matrix:
        conf:
          - Debug
          - Release
        vs-version:
          - vs2019
          - vs2022
        include:
          - vs-version: vs2019
            version-range: '16.0'
            runner: windows-2019
          - vs-version: vs2022
            version-range: '17.0'
            runner: windows-2022

    runs-on: ${{matrix.runner}}

    steps:
    - uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: ${{matrix.version-range}}

    - name: Download and Install SDL
      working-directory: RecastDemo/Contrib
      shell: pwsh
      run: |
        (new-object System.Net.WebClient).DownloadFile("https://github.com/libsdl-org/SDL/releases/download/release-2.24.2/SDL2-devel-2.24.2-VC.zip","${{github.workspace}}/RecastDemo/Contrib/SDL.zip")
        tar -xf SDL.zip
        ren SDL2-2.24.2 SDL
        del SDL.zip

    - name: Download and Install Premake
      working-directory: RecastDemo
      shell: pwsh
      run: |
        (new-object System.Net.WebClient).DownloadFile("https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip","${{github.workspace}}/RecastDemo/premake.zip")
        tar -xf premake.zip
        del premake.zip

    - name: Run Premake
      working-directory: RecastDemo
      run: ./premake5.exe ${{matrix.vs-version}}

    - name: Build
      working-directory: RecastDemo/Build/${{matrix.vs-version}}
      run: msbuild RecastDemo.vcxproj -property:Configuration=${{matrix.conf}}

  build-cmake:
    strategy:
      matrix:
        conf:
          - Debug
          - Release
        vs-version:
          - cmake-generator: Visual Studio 16 2019
            range: '[16.0,16.10)'
            runner: windows-2019
          - cmake-generator: Visual Studio 17 2022
            range: '[17.0,17.5)'
            runner: windows-2022

    runs-on: ${{matrix.vs-version.runner}}

    steps:
    - uses: actions/checkout@v3

    - name: Download and Install SDL
      working-directory: RecastDemo/Contrib
      shell: pwsh
      run: |
        (new-object System.Net.WebClient).DownloadFile("https://github.com/libsdl-org/SDL/releases/download/release-2.24.2/SDL2-devel-2.24.2-VC.zip","${{github.workspace}}/RecastDemo/Contrib/SDL.zip")
        tar -xf SDL.zip
        ren SDL2-2.24.2 SDL
        del SDL.zip

    - name: Configure CMake
      run: cmake -G "${{matrix.vs-version.cmake-generator}}" -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{matrix.conf}} -D CMAKE_INSTALL_PREFIX=${{github.workspace}}/build

    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.conf}}
